"""add_probability_and_task_tables

Revision ID: 7a66ac2bfed8
Revises: a1b2c3d4e5f6
Create Date: 2026-01-20 06:34:43.236746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a66ac2bfed8'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_template',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('task_code', sa.String(length=50), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('assignable_to', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assignable_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('can_system_execute', sa.Boolean(), nullable=False),
    sa.Column('requires_human_in_loop', sa.Boolean(), nullable=False),
    sa.Column('success_rate_threshold', sa.Float(), nullable=False),
    sa.Column('historical_success_rate', sa.Float(), nullable=True),
    sa.Column('value_tier', sa.String(length=20), nullable=True),
    sa.Column('expected_probability_lift', sa.Float(), nullable=True),
    sa.Column('always_requires_oversight', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('task_code')
    )
    op.create_table('task_step',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_code', sa.String(length=50), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('step_description', sa.Text(), nullable=True),
    sa.Column('can_system_execute', sa.Boolean(), nullable=False),
    sa.Column('requires_human_in_loop', sa.Boolean(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('depends_on_step_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_step_id'], ['task_step.step_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['task_template.template_id'], ),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_table('user_preference',
    sa.Column('preference_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('always_require_oversight', sa.Boolean(), nullable=False),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('preference_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('payment_probability',
    sa.Column('probability_id', sa.UUID(), nullable=False),
    sa.Column('patient_context_id', sa.UUID(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('overall_probability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('prob_appointment_attendance', sa.Float(), nullable=True),
    sa.Column('prob_eligibility', sa.Float(), nullable=True),
    sa.Column('prob_coverage', sa.Float(), nullable=True),
    sa.Column('prob_no_errors', sa.Float(), nullable=True),
    sa.Column('lowest_factor', sa.String(length=50), nullable=True),
    sa.Column('lowest_factor_reason', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('batch_job_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['patient_context_id'], ['patient_context.patient_context_id'], ),
    sa.PrimaryKeyConstraint('probability_id')
    )
    op.create_table('task_instance',
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('patient_context_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_type', sa.String(length=50), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('assigned_role', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expected_impact', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('batch_job_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['patient_context_id'], ['patient_context.patient_context_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['task_template.template_id'], ),
    sa.PrimaryKeyConstraint('instance_id')
    )
    op.create_table('step_instance',
    sa.Column('step_instance_id', sa.UUID(), nullable=False),
    sa.Column('task_instance_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('executed_by', sa.String(length=50), nullable=True),
    sa.Column('executed_by_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['task_step.step_id'], ),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.instance_id'], ),
    sa.PrimaryKeyConstraint('step_instance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_instance')
    op.drop_table('task_instance')
    op.drop_table('payment_probability')
    op.drop_table('user_preference')
    op.drop_table('task_step')
    op.drop_table('task_template')
    # ### end Alembic commands ###
