"""Add decision flags to patient_snapshot

Revision ID: 263b5633c96e
Revises: d9c27f4cc956
Create Date: 2026-01-19 20:12:21.917653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '263b5633c96e'
down_revision: Union[str, None] = 'd9c27f4cc956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_snapshot', sa.Column('verified', sa.Boolean(), nullable=False))
    op.add_column('patient_snapshot', sa.Column('data_complete', sa.Boolean(), nullable=False))
    op.add_column('patient_snapshot', sa.Column('critical_alert', sa.Boolean(), nullable=False))
    op.add_column('patient_snapshot', sa.Column('needs_review', sa.Boolean(), nullable=False))
    op.add_column('patient_snapshot', sa.Column('additional_info_available', sa.Boolean(), nullable=False))
    op.add_column('patient_snapshot', sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('patient_snapshot', sa.Column('extended_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('patient_snapshot', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('patient_snapshot', sa.Column('source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_snapshot', 'source')
    op.drop_column('patient_snapshot', 'created_by')
    op.drop_column('patient_snapshot', 'extended_data')
    op.drop_column('patient_snapshot', 'warnings')
    op.drop_column('patient_snapshot', 'additional_info_available')
    op.drop_column('patient_snapshot', 'needs_review')
    op.drop_column('patient_snapshot', 'critical_alert')
    op.drop_column('patient_snapshot', 'data_complete')
    op.drop_column('patient_snapshot', 'verified')
    # ### end Alembic commands ###
