"""Initial schema - PRD Phase 1

Revision ID: d9c27f4cc956
Revises: 
Create Date: 2026-01-19 18:55:51.543276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9c27f4cc956'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tenant',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('app_user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('patient_identity_ref',
    sa.Column('patient_identity_ref_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('external_patient_id_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('patient_identity_ref_id')
    )
    op.create_table('policy_config',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('allowlist_rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ui_variants_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeout_rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'version')
    )
    op.create_table('invocation',
    sa.Column('invocation_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('page_signature', sa.String(length=500), nullable=True),
    sa.Column('surface_type', sa.String(length=20), nullable=False),
    sa.Column('ui_variant_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.application_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('invocation_id')
    )
    op.create_table('patient_context',
    sa.Column('patient_context_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('patient_key', sa.String(length=255), nullable=False),
    sa.Column('patient_identity_ref_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_identity_ref_id'], ['patient_identity_ref.patient_identity_ref_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('patient_context_id'),
    sqlite_autoincrement=True
    )
    op.create_table('assignment',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('patient_context_id', sa.UUID(), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_role_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_role_id'], ['role.role_id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['patient_context_id'], ['patient_context.patient_context_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('event_log',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('patient_context_id', sa.UUID(), nullable=True),
    sa.Column('invocation_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['patient_context_id'], ['patient_context.patient_context_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('patient_snapshot',
    sa.Column('patient_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('patient_context_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('id_label', sa.String(length=100), nullable=True),
    sa.Column('id_masked', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_context_id'], ['patient_context.patient_context_id'], ),
    sa.PrimaryKeyConstraint('patient_snapshot_id')
    )
    op.create_table('session',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('invocation_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('end_reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['invocation_id'], ['invocation.invocation_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('system_response',
    sa.Column('system_response_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('patient_context_id', sa.UUID(), nullable=False),
    sa.Column('surface_type', sa.String(length=20), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('proceed_indicator', sa.String(length=20), nullable=False),
    sa.Column('execution_mode', sa.String(length=50), nullable=True),
    sa.Column('tasking_summary', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.CheckConstraint("proceed_indicator IN ('grey', 'green', 'yellow', 'blue')", name='check_proceed_indicator'),
    sa.ForeignKeyConstraint(['patient_context_id'], ['patient_context.patient_context_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('system_response_id')
    )
    op.create_table('mini_submission',
    sa.Column('mini_submission_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('patient_context_id', sa.UUID(), nullable=False),
    sa.Column('system_response_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('invocation_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('override_proceed', sa.String(length=20), nullable=True),
    sa.Column('override_tasking', sa.Text(), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.CheckConstraint("note_text IS NOT NULL AND note_text != ''", name='check_note_required'),
    sa.ForeignKeyConstraint(['patient_context_id'], ['patient_context.patient_context_id'], ),
    sa.ForeignKeyConstraint(['system_response_id'], ['system_response.system_response_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('mini_submission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mini_submission')
    op.drop_table('system_response')
    op.drop_table('session')
    op.drop_table('patient_snapshot')
    op.drop_table('event_log')
    op.drop_table('assignment')
    op.drop_table('patient_context')
    op.drop_table('invocation')
    op.drop_table('policy_config')
    op.drop_table('patient_identity_ref')
    op.drop_table('app_user')
    op.drop_table('tenant')
    op.drop_table('role')
    op.drop_table('application')
    # ### end Alembic commands ###
